"""
clash_flex_blurb.py
--------------------
Builds the caption text for /flex — a short, punchy blurb about a
Zappy's unique traits and abilities. Reuses the ability names/descs and
combo names already generated by stats_engine.py / algorand_lookup.py
rather than inventing new copy, so it always stays in sync with actual
battle mechanics.
"""

import random

OPENERS = [
    "Say hello to",
    "Meet",
    "Introducing",
    "Behold",
    "Presenting",
    "Feast your eyes on",
    "Everybody, meet",
    "Direct your attention to",
]

CLOSERS = [
    "Come at me. 😤",
    "Rate the build. 🔥",
    "This is the one. ⚡",
    "Screenshot this. 📸",
    "Undefeated in my heart, at least. 😌",
    "Try me.",
    "No notes. 💯",
    "Certified heater. 🥵",
    "Built different.",
    "Yeah, I said what I said.",
]

TRAIT_LABELS = {
    "background": "bg",
    "body": "fit",
    "earring": "earring",
    "eyes": "eyes",
    "eyewear": "eyewear",
    "head": "head",
    "mouth": "mouth",
    "skin": "skin",
}

# Avoid picking the same opener/closer twice in a row across /flex calls —
# a small fixed pool otherwise repeats surprisingly often (birthday-paradox
# effect). Tracked in-process; resets on bot restart, which is fine.
_last_opener = None
_last_closer = None


def _pick_no_repeat(pool: list, last_value: str | None) -> str:
    choices = [p for p in pool if p != last_value] or pool
    return random.choice(choices)

# Short "what it does" line per combo, pulled from the actual bonuses in
# stats_engine.check_combos() — not invented copy. combo_name strings can be
# stacked ("X + Y"), so this is looked up piece by piece.
COMBO_EFFECTS = {
    "⚡ Storm Caller":            "+20 VLT, +10 SPK",
    "🛡️ Iron Shell":             "+25 INS",
    "🎲 Lucky Fool":              "+20 SPK",
    "👑 Zappy Prime":             "+15 VLT, +15 INS, +15 SPK",
    "👑 Royal Command":           "+15 VLT, +10 INS",
    "💀 Chaos Agent":             "+25 SPK",
    "🔥 Firebrand":               "+20 VLT",
    "🥇 Gold Standard":           "+10 VLT, +10 INS",
    "📡 Signal Lost":             "+15 INS",
    "💀 Nothing Left to Lose":    "+10 SPK",
}


def combo_effect_text(combo_name: str | None) -> str:
    """'🎲 Lucky Fool + 💀 Nothing Left to Lose' -> '🎲 Lucky Fool (+20 SPK) + 💀 Nothing Left to Lose (+10 SPK)'"""
    if not combo_name:
        return ""
    parts = [p.strip() for p in combo_name.split(" + ")]
    out = []
    for p in parts:
        eff = COMBO_EFFECTS.get(p)
        out.append(f"{p} ({eff})" if eff else p)
    return " + ".join(out)


def trait_flavor(traits: dict, limit: int = 3) -> str:
    """Pick notable traits to call out for a regular Zappy."""
    notable_order = ["head", "eyewear", "earring", "skin", "background"]
    picks = []
    for key in notable_order:
        val = traits.get(key)
        if val and val not in ("None", "?", ""):
            picks.append(f"{val} {TRAIT_LABELS.get(key, key)}")
        if len(picks) >= limit:
            break
    if not picks:
        return ""
    return " · ".join(picks)


def build_flex_blurb(zappy: dict) -> str:
    """
    zappy: the dict returned by fetch_zappy_traits() — has name, stats
    (VLT/INS/SPK/abilities/combo), traits, and is_hero/is_collab flags.
    """
    global _last_opener, _last_closer

    name = zappy.get("name", "This Zappy")
    stats = zappy.get("stats", {}) or {}
    traits = zappy.get("traits", {}) or {}
    abilities = stats.get("abilities", []) or []
    combo = stats.get("combo")
    is_hero = zappy.get("is_hero", False)
    is_collab = zappy.get("is_collab", False)

    opener = _pick_no_repeat(OPENERS, _last_opener)
    _last_opener = opener
    lines = [f"{opener} **{name}**."]

    if combo:
        eff = combo_effect_text(combo)
        lines.append(f"Running the **{eff or combo}** combo.")

    for ab in abilities:
        if isinstance(ab, dict) and ab.get("name"):
            lines.append(f"⚡ **{ab['name']}** — {ab.get('desc', '')}")

    if is_hero:
        lines.append(f"One of the {zappy.get('hero_type', 'roster')} Heroes — full stats, no RNG required.")
    elif is_collab:
        lines.append("A collab Zappy — rare on top of rare.")
    else:
        flavor = trait_flavor(traits, limit=4)
        if flavor:
            lines.append(f"Wearing: {flavor}.")

    closer = _pick_no_repeat(CLOSERS, _last_closer)
    _last_closer = closer
    lines.append(closer)

    return "\n".join(lines)
